version: '3.3'

services:
  frontend:
    build: frontend
    image: fhtw-ai-frontend
    ports:
      - 80:${STREAMLIT_SERVER_PORT:-8501}
    environment:
      - APP_BACKEND_URL=http://backend
      - STREAMLIT_SERVER_PORT=${STREAMLIT_SERVER_PORT:-8501}
    depends_on:
      - backend

  backend:
    build: backend
    image: fhtw-ai-backend
    ports:
      - 8080:80