version: '3.3'

services:
  fhtw-streamlit-container:
    build: streamlit
    image: streamlit_app
    ports:
      - 80:${STREAMLIT_SERVER_PORT:-8501}
    environment:
      - STREAMLIT_SERVER_PORT=${STREAMLIT_SERVER_PORT:-8501}